@ECHO OFF
ECHO THIS BATCH IS FOR DEBUGGING THE EXECUTABLE JAR ONLY
ECHO DOUBLE-CLICK THE "matchTool.JAR" TO RUN IT
ECHO -
ECHO Generated by: JAR Maker (http://www.goldenstudios.or.id/)
@ECHO ON
java -jar matchTool.JAR
@ECHO OFF
pause
